"""Columns names changed

Revision ID: 013dc1eb851a
Revises: 2933326673cb
Create Date: 2021-12-20 11:54:06.696926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '013dc1eb851a'
down_revision = '2933326673cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'id')
    op.add_column('employees', sa.Column('full_name', sa.String(length=128), nullable=False))
    op.drop_column('employees', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('name', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('employees', 'full_name')
    op.add_column('departments', sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
